module.exports.product = require('./product')
module.exports.user = require('./user')
module.exports.session = require('./session')
module.exports.orders = require('./orders')
module.exports.newsLetter = require('./newsletter')