module.exports.product = require('./product.js')
module.exports.user = require('./user.js')
module.exports.session = require('./session.js')
module.exports.ordres = require('./ordres.js')
module.exports.newsLetter = require('./newsletter.js')